**NOTEBOOK PER LA PULIZIA E IL FILTRAGGIO DEL DATASET SUI PROGETTI FINANZIATI DAL PRIN 2022**

In [36]:
import pandas as pd

In [37]:
dataset = "../dataset/prin_2022/completo_prin_2022.csv"

prin_2022 = pd.read_csv(dataset)

In [38]:
prin_2022.head()

,codice,progetto,istituzione,finanziamento
0,202224WS4K,"GREen policy shocks, Economic transition, and ...",Università degli studi di PALERMO,314509.00
1,20222X8L5C,MANAGING SUSTAINABILITY TENSIONS FOR CHANGE,Università degli studi di PADOVA,264054.00
2,20222SBH75,Entrepreneurial ecosystem and business registr...,Università Politecnica delleMARCHE,303.29
3,20222Z3CR7,Nudging under Limited Attention,Università degli Studi di PALERMO,229638.00
4,202232ZTX7,"And Justice for All: Access to Courts, Trials,...",Università Commerciale Luigi Bocconi MILANO,226.92

Bisogna correggere il formato del finanziamento: ci sono stati evidenti errori durante lo scraping (per esempio il finanziamento per il progetto 20222SBH75 è stato di circa 303mila euro e non per 303.29)

In [39]:
prin_2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 1058 entries, 0 to 1057
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   codice         1058 non-null   str
 1   progetto       1058 non-null   str
 2   istituzione    1058 non-null   str
 3   finanziamento  1058 non-null   float64
dtypes: float64(1), str(3)
memory usage: 33.2 KB

In [40]:
prin_2022["finanziamento"] = prin_2022["finanziamento"].astype(int)

In [41]:
prin_2022.head()

,codice,progetto,istituzione,finanziamento
0,202224WS4K,"GREen policy shocks, Economic transition, and ...",Università degli studi di PALERMO,314509
1,20222X8L5C,MANAGING SUSTAINABILITY TENSIONS FOR CHANGE,Università degli studi di PADOVA,264054
2,20222SBH75,Entrepreneurial ecosystem and business registr...,Università Politecnica delleMARCHE,303
3,20222Z3CR7,Nudging under Limited Attention,Università degli Studi di PALERMO,229638
4,202232ZTX7,"And Justice for All: Access to Courts, Trials,...",Università Commerciale Luigi Bocconi MILANO,226

In [42]:
for index, row in prin_2022.iterrows():
    if len(str(int(row["finanziamento"]))) == 3:
        prin_2022.at[index, "finanziamento"] = row["finanziamento"] * 1000

In [43]:
finanziamento_medio = prin_2022["finanziamento"].mean()
int(finanziamento_medio)

252053

In [44]:
prin_2022.head()

,codice,progetto,istituzione,finanziamento
0,202224WS4K,"GREen policy shocks, Economic transition, and ...",Università degli studi di PALERMO,314509
1,20222X8L5C,MANAGING SUSTAINABILITY TENSIONS FOR CHANGE,Università degli studi di PADOVA,264054
2,20222SBH75,Entrepreneurial ecosystem and business registr...,Università Politecnica delleMARCHE,303000
3,20222Z3CR7,Nudging under Limited Attention,Università degli Studi di PALERMO,229638
4,202232ZTX7,"And Justice for All: Access to Courts, Trials,...",Università Commerciale Luigi Bocconi MILANO,226000

Il finanziamento **totale** ai progetti PRIN 2022 nei settori SH 1 - 7 è stato di circa **266 milioni di euro**

In [45]:
finanziamenti_totali = prin_2022["finanziamento"].sum()

int(finanziamenti_totali)

266672767

Il finanziamento **medio** ai progetti PRIN 2022 nei settori SH 1 - 7 è stato di circa **252 mila euro**

In [46]:
finanziamento_medio = prin_2022["finanziamento"].mean()
int(finanziamento_medio)

252053

Proviamo a filtrare i progetti nel campo delle DH

In [47]:
parole_chiave_dh = [
    #digital x
    "digital humanities", "digital archive", "digital preservation", "digital heritage",
    "digital transition", "digital mapping", "digital catalogue", "digital repertoire",
    "digital atlas", "digitisation", "metadata", "digital repository",
    "digital enhancement", "archival infrastructures", "digital curation", "digital restoration",
    "digital linguistics", "digital linguistic", "digital cartography",
    "digital reconstruction",  "virtual heritage",
    "computer vision", "digital broadcasting archives", "3D modeling",
    "digital dissemination"

    # LINGUISTICA COMPUTAZIONALE E ANALISI TESTUALE
    "computational linguistics", "computational linguistic",
    "textual", "corpus", "semantic", "syntax", "lexical", "philology", 
    "scholarly edition", "encoding", "paratext", "data-driven", "data oriented", 
    "computational", "algorithmic", "machine learning", "human-machine interaction",
    "distributional semantic analysis", "linked data", "interlinking", "text mining",
    "named entity recognition", "stylometry", "digital papyrology", "scholarly digital edition",
    "digital epigraphy", "formal models", "conceptual models",

    # --- GEOGRAFIA DIGITALE, CARTOGRAFIA E ARCHEOLOGIA ---
    "GIS", "preventive archaeology", "spatial analysis", "deep mapping",
    "historical GIS",

    "knowledge graph", "digital journalism", "data journalism",
]


parole_chiave_sh = [
    # Economia e Finanza
    "economics", "gdp", "inflation", "unemployment", "taxation", "bank", "banking", "economy",

    # Sociologia, Antropologia e Demografia
    "sociology", "demography", "migration", "inequality", "gender", 
    "ethnicity", "anthropological", "ritual", "voting",

    # Scienze Politiche, Istituzioni e Relazioni Internazionali
    "politics", "political", "democracy", "diplomacy", "institution", 
    "legislation", "regulation", "treaty",

    # Psicologia e Scienze Cognitive
    "psychology", "psychological", "cognition", "perception", 
    "anxiety", "depression", "personality",

    # Geografia Umana e Media
    "urbanization", "pedagogy"
]

In [48]:
indici_progetti_dh = []

for index, row in prin_2022.iterrows():
    progetto = row["progetto"].lower()
    
    is_dh = any(chiave_dh in progetto for chiave_dh in parole_chiave_dh)
    is_sh = any(chiave_sh in progetto for chiave_sh in parole_chiave_sh)

    if is_dh and not is_sh:
        indici_progetti_dh.append(index)

In [49]:
df_progetti_dh = prin_2022.loc[indici_progetti_dh].reset_index(drop=True)

df_progetti_dh

,codice,progetto,istituzione,finanziamento
0,2022KFLF3E,"EquAl: Equitable Algorithms, Promoting Fairnes...",Università degli studi di BOLOGNA,242691
1,20228W9NE7,Caring for Children with an Immigrant Backgrou...,Università degli studi di ROMA La Sapienza,220000
2,202297CKET,ALGOLIT: Understanding and boosting algorithmi...,Università degli Studi di TRENTO,197997
3,2022YRJ83A,Feedback culture: assessing the effects of alg...,Università degli Studi di MILANO,211378
4,2022Z78M8J,The Digital Transition and the World of Work: ...,Università degli studi di BARI ALDO MORO,246248
5,202233C93X,MetaLing Corpus: Creating a corpus of English ...,Università degli Studi di MILANO,106675
6,202249CYPP,A.L.AR..CO (Archivio Linguistico ARbëresh e lt...,Università della CALABRIA,325376
7,20225MH5NM,Disentangling heteRogeneity in autism: from EA...,Università degli Studi di TRIESTE,295202
8,20225PJ2JM,Interactions between visuo-spatial attention a...,Università degli studi di ROMA La Sapienza,248000
9,2022A74X79,Corpus SIM (Senectus Ipsa Morbus) - Spontaneou...,Università degli studi di Napoli Federico II,255106
10,2022APAFFN,The attentional curve of forgetting visual inf...,Università degli Studi di ROMA La Sapienza,187000
11,2022K744JB,CROss-linguistic interference in the assignmen...,Università degli studi di MILANO-BICOCCA,182085
12,2022NPXYHH,CIP - Corpus of Italian language for Preschool...,Università degli studi di MODENA e REGGIO EMILIA,271736
13,2022S9ZMAY,PARALLEL SEMANTIC READING OF MULTIPLE WORDS DU...,Università degli studi di MILANO-BICOCCA,212478
14,2022THXT58,Computational and linguistic benchmarks for th...,Università di PISA,186358
15,2022WHZJ98,The lexicalization of the adjective class in I...,Università degli studiGuglielmo Marconi -Telem...,339298
16,2022YMARNM,"Repertory of courts. Language, languages and c...",Università degli studi di Urbino Carlo Bo,256312
17,2022YWWCP7,ARDIPSArchivio Digitale delltaliano Parlato-sc...,Università degli studi di CATANIA,303764
18,2022X37WMB,Prediction of psychopathological outcome and p...,Università degli studi di PALERMO,255107
19,20223H7759,Literary translation and cultural transfer bet...,Università degli Studi di PADOVA,201697
20,20224K2JA8,HYPERsTAGE: an Open Knowledge base for the sem...,Università degli studi di ROMA Tor Vergata,259346
21,20225KT494,The Primo Levi Thesaurus: The Genesis and Diss...,Università degli studi di PAVIA,270000
22,20227M8RS7,The ATLAS of talian Digital Humanities: a dyna...,Università degli studi di BOLOGNA,212764
23,202283FJF7,Texts of Uncertain Authorship in Thirteenth-ce...,Università degli studi di ROMA Tor Vergata,265000
24,20228TEZ9T,The forms of the museum: pilot project for a d...,Università degli studi di Napoli Federico II,271737
25,20228Z4LX3,CoenoBl(u)M. Art and architecture of the Cassi...,Università degli studi di PADOVA,243142
26,2022A2LXSP,"IDEA | THE DIGITAL ZUCCARI CORPUS. Texts, Cont...",Università degli studi di TORINO,252945
27,2022A773E4,Peripheral Baroque Sculpture 1630-1750: knowle...,Università degli studi di FIRENZE,238000
28,2022ARJYES,A NEW OPEN ACCESS CRITICAL EDITION OF DANTES C...,Università degli Studi di FERRARA,239726
29,2022CW8EYT,ArDiTeHis (Digital Archive of Spanish Text) an...,Università degli studi di CATANIA,200691
30,2022EK7P7F,The CLALI project: a corpus for studying the l...,Università degli studi di ROMA La Sapienza,200113
31,2022FNR3ZJ,Digital Bandello: Scholarly Edition and Commen...,Università degli studi di MODENA e REGGIO EMILIA,218676
32,2022HE32C5,DAEL - Digital Archive of Eighteenth-century L...,Università degli studi di PADOVA,223918
33,2022HE8ZHS,"Detached frescoes, conservation and museum set...",Università degli Studi di VERONA,260621
34,2022HJW23K,RETI REndering Texts and Images. Digital Schol...,Università di PISA,228408
35,2022J4ER9X,A Pilot Project in the Digitisation of Epigrap...,Università degli studi di FIRENZE,178198
36,2022NE2LWP,"ParaText – Refining methods, tuning tools, enh...",Università degli studi di PAVIA,242708
37,2022PXTYCL,M.A.R.E: Manuscripts and books from Asia Reach...,Università di PISA,283285
38,2022PCRLJ9,Vitruvius De Architectura in the Classical and...,Università degli studi di BOLOGNA,257145
39,2022R4PYH3,Marco Polo - from Venice to World Literatures ...,Università Ca' FoscariVENEZIA,187041
40,2022RFC5ZR,The Dante Ancient Commentaries Corpus (CoDA). ...,Università degli studi di Napoli Federico II,244273
41,2022SA97FP,Early Modern Spanish Theater (1570 - 1700): te...,Università degli Studi ROMATRE,270923
42,2022TBN35M,Web-based Textual Corpus of Central-Italian Di...,Università degli studi G.d'AnnunzioCHIETI-PESCARA,263997
43,2022Y9S3H4,Textual Data and Tools for Coreference Resolut...,Università Cattolica delSacro Cuore,220622
44,2022S5LET5,The textual legacy of the Ostrogoths in taly: ...,Università degli studi di PERUGIA,312946
45,2022SYRN27,ArDIRe. Digital archives and dictionary for th...,Università degli Studi di TORINO,228534
46,2022EA8FC7,The Digital Kennicot: Textual Transmission of ...,Università degli studi di TORINO,250000
47,2022TF9CK2,Corpus of the Medieval and Renaissance Scribes...,Università degli studi di FIRENZE,331278
48,2022XTSEZ3,ON: Objects in network.The social life of thin...,Università degli studi di BOLOGNA,252000
49,2022CCEA2R,Synchronized with Nature. Measuring time in an...,Università degli studi di ROMA La Sapienza,320000
50,2022ZKKW4F5,The geography of the “twin transition: mapping...,Università degli studi di PADOVA,247000

In [50]:
print(f"Trovati {len(df_progetti_dh)} progetti di Digital Humanities:")

for index, row in df_progetti_dh.iterrows():
    print(f"{index+1} -> {row["progetto"]}")

Trovati 51 progetti di Digital Humanities:
1 -> EquAl: Equitable Algorithms, Promoting Fairness and Countering AlgorithmicDiscrimination Through Norms and Technologies.
2 -> Caring for Children with an Immigrant Background: A Cross-Sequential Longitudinal Study on Kindness Pillars and the Role of Dispositional and Contextual Factors inEarly Childhood
3 -> ALGOLIT: Understanding and boosting algorithmic literacy
4 -> Feedback culture: assessing the effects of algorithmic recommendations onplatformized consumption - ALGOFEED
5 -> The Digital Transition and the World of Work: Labour markets, Organizations, Jobquality and Industrial Relations
6 -> MetaLing Corpus: Creating a corpus of English linguistics metalanguage from the16th to the 18th century
7 -> A.L.AR..CO (Archivio Linguistico ARbëresh e ltalo-romanzo in COntatto)Testo italianoA.L.AR.l.Co (Arberesh and Italo-Romance language corpus in contact)
8 -> Disentangling heteRogeneity in autism: from EArly behavioral markers toindividual treatment responses through a Machine learning approach (DREAM).
9 -> Interactions between visuo-spatial attention and semantic memory in large-scalecortical networks
10 -> Corpus SIM (Senectus Ipsa Morbus) - Spontaneous speech in healthy ageing
11 -> The attentional curve of forgetting visual information in younger and older adults:experimental and computational insights.
12 -> CROss-linguistic interference in the assignment of meaning during sentencecomprehension in bilINGual speakers: investigating semantic and syntactic processing and thecase of code-switching (CROssING)
13 -> CIP - Corpus of Italian language for Preschoolers.Lexicon directed to Italian preschool children from 3 to 6 years collected from heterogeneoussources in Italian and Italian Sign Language
14 -> PARALLEL SEMANTIC READING OF MULTIPLE WORDS DURING THE LIFE-SPAN
15 -> Computational and linguistic benchmarks for the study of verb argumentstructure
16 -> The lexicalization of the adjective class in Indo-European and Semitic
17 -> Repertory of courts. Language, languages and cultural textuality ReCoLLeCT
18 -> ARDIPSArchivio Digitale delltaliano Parlato-scritto (1860-1953)Digital Archive of Spoken-Written Italian (1860-1953)
19 -> Prediction of psychopathological outcome and parental rflective functioningbased on perinatal risk factors: a machine learning quanti-qualitative longitudinal study onmothers and fathers
20 -> Literary translation and cultural transfer between Italy and Romania: creation ofa bilingual digital archive of literary translations from Italian into Romanian and from Romanianinto Italian
21 -> HYPERsTAGE: an Open Knowledge base for the semantic reconstruction of theatrical performances through the harvesting and processing resources from the New ItalianNetwork of theatrical digital archives.
22 -> The Primo Levi Thesaurus: The Genesis and Dissemination of a Twentieth-CenturyCorpus
23 -> The ATLAS of talian Digital Humanities: a dynamic knowledge graph of digitalscholarly research on Italian Cultural Heritage
24 -> Texts of Uncertain Authorship in Thirteenth-century Italian Lyric Poetry. Methods,Practices and Tools of Attributive Philology.
25 -> The forms of the museum: pilot project for a digital atlas of talian museums
26 -> CoenoBl(u)M. Art and architecture of the Cassinese Benedictine Congregation (XV-×XVIll centuries): digital and spatial analysis strategies through BiM models.
27 -> IDEA | THE DIGITAL ZUCCARI CORPUS. Texts, Contexts, Sources and Lexicon
28 -> Peripheral Baroque Sculpture 1630-1750: knowledge and engagement.Census and Digital Atlas of the Lazio provinces and the border areas
29 -> A NEW OPEN ACCESS CRITICAL EDITION OF DANTES COMMEDIA FOSTERINGDIGITAL HUMANITIES PROJECTS. COLLATION OF 580 MSS, PROVISIONAL TEXTS ANDAPPARATUSES, AND LEXICAL UPDATINGS TO THE VOCABOLARIODANTESCO (AcCADEMIA DELLA CRUSCA/ CNR)
30 -> ArDiTeHis (Digital Archive of Spanish Text) and the digital editions of certainSpanish texts from the XVI to the XiX centuries
31 -> The CLALI project: a corpus for studying the language of autographs of Italianwriters (1450-1550).
32 -> Digital Bandello: Scholarly Edition and Commentaries.
33 -> DAEL - Digital Archive of Eighteenth-century Letters
34 -> Detached frescoes, conservation and museum setings. Historical research, non- invasive diagnostic and Digital Heritage for a new inclusive Museology.
35 -> RETI REndering Texts and Images. Digital Scholarly Editions with EditionVisualization Technology
36 -> A Pilot Project in the Digitisation of Epigraphic Manuscripts (ProDEM): Senator Filipo Buonarrots Papers and Antiquarian Culture under the Last Medicis
37 -> ParaText – Refining methods, tuning tools, enhancing book heritage for the studyof the relationship between text and exegesis in manuscripts of ancient Greek poetry.
38 -> M.A.R.E: Manuscripts and books from Asia Reaching Europe. A semanticallyenhanced digital library mapping Asian books circulation along the silk Maritime Routes.
39 -> Vitruvius De Architectura in the Classical and in the Early Modern Age. Philology,Archaeology, Digital Library, and 3D Modelling
40 -> Marco Polo - from Venice to World Literatures (MarVeLs). Textual, inguistic, andsocio-cultural factors in the spreading of Devisement dou monde through space and time(13th-16th centuries).
41 -> The Dante Ancient Commentaries Corpus (CoDA). Digital Tools for Lexicographyand Exegesis of the Commedia.
42 -> Early Modern Spanish Theater (1570 - 1700): textual transmission, europeancirculation, new digital resources
43 -> Web-based Textual Corpus of Central-Italian Dialects (CorTIM)
44 -> Textual Data and Tools for Coreference Resolution of Latin
45 -> The textual legacy of the Ostrogoths in taly: The Bible version and other texts(Acronym: LegOst)
46 -> ArDIRe. Digital archives and dictionary for the early artistic recipe books in theItalian Language (late 14th-16th century)
47 -> The Digital Kennicot: Textual Transmission of the Hebrew Bible in the Middle Ages- DiKe (TexTHBM)
48 -> Corpus of the Medieval and Renaissance Scribes in Italy (Scriblt)
49 -> ON: Objects in network.The social life of things in the fifteenth century between notarial sources and semantic web
50 -> Synchronized with Nature. Measuring time in ancient Egypt and Mesopotamia:archaeological and textual evidence
51 -> The geography of the “twin transition: mapping the regional combination of thegreen and the digital transition - GEoTWIN

In [51]:
finanziamenti_progetti_DH = df_progetti_dh["finanziamento"].sum()
int(finanziamenti_progetti_DH)

12419545